// The trivia shown under "What are we shipping today?" on the new-session
// pane, one fact picked at random each time the pane mounts. Every entry has
// to teach you something: a name, a date, or a number you could look up. A
// dry closing line is welcome, but the fact has to stand without it.
// One line per fact.
export const FACTS: readonly string[] = [
  'The first computer "bug" was literal: a moth taped into the Harvard Mark II logbook in 1947, with the note "first actual case of bug being found."',
  'Python is named after Monty Python, not the snake. Guido van Rossum was reading the scripts while building it.',
  'The Apollo 11 guidance computer had about 4KB of RAM. Your terminal prompt is using more memory than the moon landing did.',
  'In 1996, a $370 million Ariane 5 rocket exploded because of a 64-bit float being stuffed into a 16-bit integer.',
  '"Ada", the language, is named after Ada Lovelace, who wrote the first published algorithm in 1843 for a computer that was never built.',
  'Linus Torvalds also wrote Git in about two weeks, mostly because he was annoyed at every existing version control system.',
  "The QWERTY layout was designed partly to slow typists down so mechanical typewriter arms wouldn't jam. We just never stopped using it.",
  'NASA still flies code written in the 1970s: the Voyager probes get patches from billions of miles away, at 160 bits per second.',
  'The "404" error is just HTTP\'s fourth class of status code, fourth entry. The legend about a "room 404 at CERN" is itself a 404: not found.',
  "Windows 95 had a timer bug that crashed the OS after exactly 49.7 days of uptime. Nobody noticed for years because nobody's Windows 95 stayed up that long.",
  'JavaScript was built in 10 days. It now runs most of the visible internet. Sleep well.',
  'A single bit flipped by a cosmic ray once gave a Belgian election candidate 4,096 extra votes. The universe has write access to your RAM.',
  "There's a number so illegal that publishing it was a crime: the AACS encryption key. People printed it on t-shirts anyway.",
  'Grace Hopper handed out foot-long wires to explain a nanosecond: that\'s how far light travels in one. She kept a "microsecond" coil of wire that was 984 feet.',
  'In binary, 42 is 101010. Douglas Adams claimed the choice was a joke with no meaning. Fans refuse to believe him to this day.',
  'The Y2K bug cost an estimated $300+ billion to fix, worked, and is now remembered as a hoax because it worked.',
  '"Bluetooth" is named after a 10th-century Viking king, Harald Bluetooth, who united Denmark and Norway. The logo is his initials in runes.',
  'The first hard drive shipped in 1956. It stored 5MB, weighed about a ton, and was moved by forklift. IBM leased it for $3,200 a month.',
  'Vim\'s license asks you to consider donating to orphans in Uganda. Its author, Bram Moolenaar, called it "charityware."',
  'The word "robot" comes from the Czech word for forced labor. It first appeared in a 1920 play where the robots revolt. We used the name anyway.',
  "Dennis Ritchie co-created C and Unix. He died the same week as Steve Jobs and got a fraction of the news coverage. Every tribute to Jobs was typed on Ritchie's work.",
  'Ada Lovelace was asked to translate a paper about the Analytical Engine. Her notes ended up three times longer than the paper. The first case of scope creep.',
  '"Debugging is twice as hard as writing the code in the first place," wrote Brian Kernighan. So if you write the cleverest possible code, you cannot debug it.',
  'The Unix epoch began January 1, 1970. On January 19, 2038, 32-bit timestamps overflow. Y2K fans call it "the sequel."',
  'The @ symbol was a dying accounting character until 1971. Ray Tomlinson picked it to separate user from machine in the first email address.',
  'Google was misspelled. The founders meant "googol," the number 1 followed by 100 zeros, and registered the typo.',
  'The first banner ad ran in 1994. It said "Have you ever clicked your mouse right HERE?" and 44% of people clicked. It has been downhill ever since.',
  'Space Invaders sped up as you killed aliens because the hardware had less to draw. The bug became the difficulty curve.',
  'Pac-Man breaks on level 256 because the level counter is a single byte. The kill screen is an integer overflow you can visit.',
  'Walk far enough in old Minecraft and the terrain turned to glitchy chaos, the "Far Lands." That was floating point math running out of precision.',
  'The Konami Code was written by Kazuhisa Hashimoto, who was porting Gradius and could not beat his own game while testing it. He added a cheat and forgot to remove it.',
  'Mario has a mustache because 1981 pixels could not draw a mouth. He wears a hat because they could not animate hair.',
  'Wi-Fi does not stand for anything. A branding agency made it up to sound like "hi-fi." People invented "wireless fidelity" after the fact.',
  'CAPTCHA stands for "Completely Automated Public Turing test to tell Computers and Humans Apart." You have failed one before. Think about that.',
  'The first 1GB hard drive shipped in 1980. It cost $40,000 and weighed 550 pounds. Today a gigabyte falls out of your pocket.',
  'Junk mail is called "spam" because of a Monty Python sketch. Vikings chant "spam" until nobody can talk. That is also how your inbox works.',
  'A "jiffy" is a real unit of time. The Linux kernel uses it for its clock tick. "Back in a jiffy" is a promise you can measure.',
  'The Boeing 787 had a counter that overflowed after 248 days and cut electrical power. The fix: reboot the plane on a schedule. Turn it off and on again, but with paperwork.',
  'The first domain name ever registered was symbolics.com, in 1985. It is still up, as a museum of itself.',
  'IPv4 has about 4.3 billion addresses, and we ran out. IPv6 has enough to give every grain of sand on Earth trillions of them. We should be fine for a bit.',
  'Rubber duck debugging is real and it works. Explaining your code out loud to a duck forces you to actually read what you wrote.',
  'Excel thinks 1900 was a leap year. It was not. Lotus 1-2-3 had the bug first, and Excel copied it on purpose to stay compatible. The bug is older than most of its users.',
  'Scientists renamed human genes like SEPT1 and MARCH1 because Excel kept turning them into dates. The spreadsheet won.',
  'Background processes are called "daemons" after Maxwell\'s demon in physics: an invisible worker that never stops. Pronounce it however you want. Everyone else does.',
  "Gangnam Style got so many views it overflowed YouTube's 32-bit counter in 2014. Google had to upgrade to 64 bits.",
  'The first six programmers of the ENIAC were all women. They programmed it by rewiring it. The job title "programmer" did not exist yet.',
  'Margaret Hamilton printed out her Apollo flight code, and the stack stood as tall as she did. She also coined the term "software engineering."',
  'Ken Thompson showed how to hide a backdoor in a compiler so well that recompiling cannot remove it. His conclusion: you cannot fully trust code you did not write yourself.',
  'The Mars Climate Orbiter burned up because one team used pounds and another used newtons. A missing unit conversion cost $327 million.',
  'ENIAC went operational in December 1945 with about 18,000 vacuum tubes. It weighed 30 tons, drew 150 kilowatts, and managed roughly 5,000 additions per second.',
  'Grace Hopper delivered the A-0 compiler in 1952, arguing that computers could translate human-readable code. She was told for years that this was impossible.',
  'Charles Babbage started designing the Difference Engine in 1822, then the Analytical Engine, which had punched cards, branching, and loops. He never finished either one.',
  "Turing's 1936 paper on computable numbers defined the algorithm and the limits of computation, before any of the machines existed.",
  'Konrad Zuse finished the Z3 on May 12, 1941, in Berlin. It was the first working programmable computer, and it already did floating point.',
  'Bardeen, Brattain, and Shockley demonstrated the first working transistor at Bell Labs on December 23, 1947. It won them the 1956 Nobel Prize in Physics.',
  'Jack Kilby demonstrated the first working integrated circuit at Texas Instruments on September 12, 1958, using germanium and gold wire.',
  'Blaise Pascal built a mechanical calculator in 1642, at age 18, to help his father with tax work. About 20 of them were ever finished.',
  "UNIVAC I called the 1952 Eisenhower landslide within 3.5% of the popular vote. CBS didn't trust it enough to air the prediction at first.",
  'Colossus Mark 1 went live at Bletchley Park in January 1944 with 1,600 valves, chewing through up to 5,000 characters per second.',
  'The Apple II shipped in April 1977 at $1,298 for 4 kilobytes of RAM. It stayed in production for 16 years and sold around 6 million units.',
  'IBM announced the System/360 on April 7, 1964. It made the 8-bit byte standard, and code written for it can still run on IBM Z mainframes today.',
  'The IBM Personal Computer launched on August 12, 1981 at $1,565 with an Intel 8088. It shipped over 750,000 units in two years.',
  'Herman Hollerith patented punched-card tabulation in 1889 and founded the company that became IBM in 1911. Your CSV import has deep roots.',
  'The Xerox Alto arrived on March 1, 1973 with a GUI, a mouse, Ethernet, and WYSIWYG editing. Xerox built about 2,000 and sold none of them.',
  'The Macintosh 128K shipped January 24, 1984 at $2,495 with a Motorola 68000, and effectively created desktop publishing.',
  'Donald Knuth started The Art of Computer Programming in 1962 and published Volume 1 in 1968. He then wrote TeX because he hated how the typesetting looked.',
  'Niklaus Wirth designed Pascal in 1970 and won the 1984 Turing Award. He liked to point out that Americans read his name by value and Europeans by reference.',
  'Douglas Engelbart filed the mouse patent in 1967 and demoed it on December 9, 1968, alongside hypertext, video calling, and screen sharing. The first mouse was made of wood.',
  'The Altair 8800 sold as a $439 kit in December 1974 with an Intel 8080 and 256 bytes of memory. Microsoft was founded to write software for it.',
  'The first ARPANET host-to-host connection went up at 10:30 pm on October 29, 1969. They typed "login," got as far as "lo," and the system crashed.',
  'Paul Mockapetris invented DNS in 1983 at USC, specified in RFC 882 and RFC 883. Before that, every host on the internet was listed in one file.',
  'Tim Berners-Lee invented the World Wide Web at CERN in 1989 and put it on the public internet on August 23, 1991. CERN put the software in the public domain.',
  'Mosaic shipped in April 1993 and was the browser that made the web mainstream. It could show images inline, which was the killer feature.',
  'Vint Cerf and Bob Kahn published the design for TCP/IP in May 1974. They received the Turing Award for it 30 years later.',
  'RFC 1 was written by Steve Crocker of UCLA and published April 7, 1969. It was titled "Host Software" and read like a polite suggestion.',
  'TAT-8 opened in 1988 as the first transatlantic fiber-optic cable to carry internet traffic. It could handle 40,000 phone calls at once.',
  'Amazon S3 launched on March 14, 2006, as one of the first generally available cloud services. Half the internet now has a bucket somewhere.',
  'Usenet was built in 1980 by Tom Truscott and Jim Ellis at Duke and UNC. It invented threaded discussion, flame wars, and FAQs.',
  'Mike Muuss wrote ping in December 1983, in about a thousand lines, and named it after sonar. He wrote it to debug a misbehaving network.',
  'Van Jacobson wrote traceroute in 1987 after Steve Deering suggested the trick of abusing the IP time-to-live field on purpose.',
  'Gopher launched in 1991 at the University of Minnesota and was beating the web for a while. In February 1993 the university announced licensing fees, and it died.',
  'Tatu Ylonen released SSH in July 1995 after a password sniffing attack on his university network. By the end of that year it had 20,000 users in 50 countries.',
  'SMTP was defined in RFC 788 in November 1981. The protocol delivering your email is older than the IBM PC hard disk.',
  'Mark Crispin designed IMAP in 1986 so mail could live on the server instead of being downloaded and deleted. Webmail owes him.',
  'BGP, the protocol that routes the entire internet, was sketched out at an IETF meeting in Austin in January 1989. The original design was written on two napkins.',
  'Twitter was built in early 2006 and launched publicly on July 15, 2006. The 140-character limit existed because SMS allowed 160.',
  'Netscape Navigator shipped in 1994 and introduced JavaScript to the world a year later. At its peak it had about 90% of the browser market.',
  'C is called C because it replaced a language called B, which came from BCPL. Dennis Ritchie built it at Bell Labs around 1972, and it was standardized as C89 in 1989.',
  'Rust is named after the fungus. Graydon Hoare picked it because rusts are "over-engineered for survival," which is the point of the language. Rust 1.0 shipped May 15, 2015.',
  'Go was started at Google in 2007 by Robert Griesemer, Rob Pike, and Ken Thompson, reportedly while waiting on a slow C++ build. Version 1.0 landed March 28, 2012.',
  'Java was called Oak, after a tree outside James Gosling\'s window, until trademark problems forced a rename. The team picked Java after the coffee. Version 1.0 shipped in 1996.',
  'PHP stood for "Personal Home Page" when Rasmus Lerdorf wrote it in 1995 to track visits to his resume. In 1997 it was redefined as "PHP: Hypertext Preprocessor," a recursive acronym.',
  'Larry Wall released Perl 1.0 on December 18, 1987. He wanted to call it "Pearl," found the name taken, and dropped a letter.',
  'Ruby is named after a birthstone. Yukihiro Matsumoto and a colleague chose it over "Coral" in a chat on February 24, 1993, and the first public release came in December 1995.',
  'John McCarthy created Lisp in 1958 and published the design on April 1, 1960. Steve Russell then realized the eval function in the paper could just be implemented directly.',
  'Grace Hopper advised the COBOL committee but did not write the language. Jean Sammet, who was there, said Hopper was "not the mother, creator, or developer of COBOL."',
  'John Backus led the IBM team that invented Fortran, starting in 1953. He said he did it because he was lazy and did not enjoy writing programs. It won him the 1977 Turing Award.',
  'Emacs was written in 1976 by David A. Moon and Guy L. Steele Jr. as a set of macros for the TECO editor. GNU Emacs, from 1985, was the first program the GNU Project released.',
  'Bill Joy wrote vi at Berkeley in 1976, adding a full-screen visual mode to the line editor ex. The name is literally the ex command for entering visual mode.',
  'Lee McMahon wrote sed at Bell Labs around 1973. It streams text past a small program instead of loading the file, which is why it still handles files bigger than your RAM.',
  'Subversion was started by CollabNet in 2000 with the explicit goal of being CVS without the bugs. Version 1.0 shipped in February 2004.',
  'Olivia Mackall announced Mercurial on April 19, 2005, days after BitKeeper withdrew its free version, the same event that triggered Git. The name is a jab: someone had called Larry McVoy mercurial.',
  'Linus Torvalds announced Linux on August 25, 1991, calling it a hobby project that would not be big. Version 1.0, in March 1994, had 176,250 lines of code.',
  'Unix was rewritten in C in 1973. That is the moment an operating system stopped being tied to one machine, and the reason you can run it on anything.',
  'AWK is named after its authors: Aho, Weinberger, and Kernighan, who built it at Bell Labs in 1977. It is still the fastest way to sum a column.',
  'Gerald Sussman and Guy Steele created Scheme at MIT in 1975 while trying to understand the actor model. They accidentally showed that lambda was enough.',
  'Haskell is named after the logician Haskell Curry, and version 1.0 arrived in 1990. It was designed by committee, which for once worked.',
  'Alan Kay and his team built Smalltalk at Xerox PARC starting in 1972, and Smalltalk-80 spread the ideas. Almost every object-oriented language is downstream of it.',
  'John Kemeny and Thomas Kurtz created BASIC at Dartmouth in 1964 so that students who were not scientists could use a computer. It worked, thoroughly.',
  'Unicode 1.0 was published in October 1991 with 7,161 characters. It now has over 150,000, and people still fight about the emoji.',
  'Donald Chamberlin and Raymond Boyce designed SQL at IBM in 1974, and it was standardized in 1986. It is older than the compact disc.',
  'The first version control system, SCCS, was written by Marc Rochkind at Bell Labs in 1972. RCS followed in 1982, and it still ships on most Unix machines.',
  'John Ousterhout wrote Tcl in 1988 because every research tool at Berkeley was inventing its own bad scripting language. He wrote one good one to embed instead.',
  'Firefox began as Phoenix 0.1 in September 2002, built from the Netscape code released as open source in 1998. It was renamed twice for trademark reasons.',
  'Knight Capital lost $440 million in 45 minutes on August 1, 2012. A deploy reached 7 of 8 servers, and a reused flag woke up dead code named Power Peg.',
  'Mariner 1 was destroyed 294 seconds after launch on July 22, 1962, an $18.5 million loss. A single missing overbar in the guidance equations was transcribed wrong.',
  'Intel took a $475 million charge in January 1995 for the Pentium FDIV bug: five missing entries in a division lookup table. Intel had argued a typical user would hit it once every 27,000 years.',
  'Heathrow Terminal 5 opened on March 27, 2008 with a baggage system that had never been tested at load. Over 10 days, 500 flights were cancelled and 42,000 bags missed their planes.',
  'One WAF regex took down much of the internet for 27 minutes on July 2, 2019. Catastrophic backtracking pinned every HTTP-serving CPU core Cloudflare had at 100%.',
  'The big AWS S3 outage of February 28, 2017 started with a typo in a documented playbook that removed too many servers. AWS could not update its own status page, because the page ran on S3.',
  'Facebook, Instagram, and WhatsApp disappeared for about six hours on October 4, 2021 after a maintenance command withdrew their BGP routes. Engineers struggled to get in the building, because the badge readers were also on that network.',
  "On January 15, 1990, a misplaced break statement collapsed all 114 of AT&T's long-distance switches for nine hours. Roughly half of 148 million calls failed, and the bug shipped inside a reliability upgrade.",
  'A bad CrowdStrike config file on July 19, 2024 caused an out-of-bounds read and blue-screened about 8.5 million Windows machines. Each one needed a human to touch it.',
  'On August 15, 2010, an integer overflow created 184 billion bitcoin in block 74638, against a 21 million cap. A patched client shipped within about five hours and the chain forked the coins away.',
  'During the flash crash of May 6, 2010, the Dow fell 998.5 points in minutes. Accenture briefly traded at one cent, and Apple printed at over $100,000 a share.',
  "Every Zune 30 on Earth froze on December 31, 2008 because a clock driver looped forever on day 366 of a leap year. Microsoft's official fix was to let the battery die and wait for January 1.",
  'The 2003 Northeast blackout cut power to 55 million people, and the trigger was a race condition in an alarm system. Operators flew blind for over an hour because the alarms had failed silently first.',
  'The Morris worm of November 2, 1988 was meant to be harmless but reinfected machines 14% of the time anyway, crashing about 6,000 systems. Its author took the first felony conviction under the Computer Fraud and Abuse Act.',
  'The Vancouver Stock Exchange index truncated instead of rounding after every trade. Started at 1000 in January 1982, it bled down to 524.811 by November 1983 purely from rounding error.',
  'In March 2016 a developer unpublished left-pad, an 11-line npm package, over a naming dispute. Builds broke across Babel, React, and much of the industry until npm restored it about two hours later.',
  "On day 18 of its mission, January 21, 2004, the Spirit rover started rebooting over 60 times: flash filesystem metadata, including long-deleted files, had consumed all its RAM. NASA fixed it from 170 million kilometers away.",
  'In 1998 an errant rm -rf deleted about 90% of Toy Story 2, and the backups had been failing silently for a month. The film survived on the home computer of Galyn Susman, who was working remotely with a new baby.',
  'The SQL Slammer worm of January 2003 fit in a single 376-byte UDP packet and infected 75,000 hosts in about 10 minutes. The patch had been available for six months.',
  'Windows Azure went down on February 29, 2012 because certificate expiry was computed by adding one to the year, producing February 29, 2013, a date that does not exist.',
  'For about 40 minutes on January 31, 2009, Google flagged every result on the internet as harmful. Someone had added "/" to the malware blocklist, and "/" matches every URL.',
  'The 2017 leap second made time briefly run backward for Cloudflare, and Go code subtracting timestamps panicked on a negative number. At peak, 0.2% of DNS queries failed. The patch was one character.',
  'On January 31, 2017 a GitLab engineer ran a delete against the production database instead of the replica, losing 300 GB. All five backup mechanisms turned out to be broken, and they recovered from a six-hour-old snapshot someone had taken by hand.',
  'The Intel 4004, the first microprocessor sold commercially, shipped November 15, 1971 with 2,300 transistors and a 740 kHz clock.',
  'The Cray-1, installed at Los Alamos in 1976, cost about $7.9 million and hit 160 MFLOPS. The padded bench around its base was hiding the power supplies.',
  'The Cerebras WSE-3, released in 2024, is a single wafer-sized chip with 4 trillion transistors and 900,000 cores. Normal chips are diced up. This one is not.',
  'The Intel 1103, launched October 1970, was the first commercial DRAM chip. It held one kilobit and killed magnetic core memory within a few years.',
  'Tape is not dead: a record 176 exabytes of LTO tape capacity shipped in 2024, and a single LTO-9 cartridge holds 18 TB before compression.',
  "IBM's Model M keyboard arrived in 1985 with buckling spring switches, and Unicomp still manufactures new ones on updated tooling.",
  'Gordon Moore published his observation in Electronics magazine in 1965, predicting a yearly doubling of transistors. He revised it to every two years in 1975, and that is the version everyone quotes.',
  'Frontier at Oak Ridge broke the exascale barrier in 2022 at 1.102 exaFLOPS. El Capitan passed it in November 2024 at 1.809 exaFLOPS.',
  'High-capacity hard drives are sealed and filled with helium, which is about a seventh the density of air, so the platters meet less drag. The first one, a 6 TB drive, shipped in 2013.',
  'A "1.44 MB" floppy actually holds 1,474,560 bytes, which is neither 1.44 million bytes nor 1.44 MiB. The label mixed decimal and binary units and nobody fixed it.',
  "Apple's M1, from 2020, has 16 billion transistors. That is about 7 million times the count of the Intel 4004 from 1971.",
  "IBM's Simon, released August 16, 1994 at $899, was the first smartphone. Its touchscreen ran for about an hour per charge.",
  'Fujio Masuoka invented flash memory at Toshiba around 1980. A colleague named it "flash" because the erase cycle reminded him of a camera flash.',
  'An estimated 13 sextillion MOS transistors were made between 1960 and 2018, which makes the transistor the most manufactured object in human history.',
  'An ASML EUV lithography machine costs around $180 million and weighs nearly 200 tons. It makes 13.5 nm light by blasting molten tin droplets with a laser tens of thousands of times a second.',
  "In March 2000, AMD's Athlon became the first x86 chip to reach 1 GHz, beating Intel to the milestone by days.",
  "The Apollo Guidance Computer's program memory was core rope: 36,864 words physically woven by threading wire through magnetic cores. The software was literally hand-sewn.",
  'Ctrl-Alt-Delete was invented in 1981 by IBM engineer David Bradley, who later said, "I may have invented it, but I think Bill made it famous."',
  'Semiconductor-grade silicon is refined to 99.9999999% purity, known in the industry as nine nines, before it is sliced into 300 mm wafers.',
  'The Cray-2 of 1985 cooled itself by fully immersing its circuit boards in liquid Fluorinert, which earned it the nickname Bubbles.',
  'The GRiD Compass of 1982 was the first clamshell laptop, cost $8,150, and flew on the Space Shuttle. NASA had a higher budget than you.',
  "NASA's Perseverance rover and the James Webb Space Telescope both run on the RAD750, a radiation-hardened PowerPC that tops out near 200 MHz.",
  'The first webcam watched a coffee pot at Cambridge starting in 1991 so researchers would stop walking to an empty pot. It went on the web in 1993, was switched off in 2001, and the pot sold on eBay for 3,350 pounds.',
  'id Software released Doom on December 10, 1993 by uploading it to a University of Wisconsin FTP server. So many people connected at once that the university network fell over.',
  'By late 1995 analysts thought Doom was installed on more PCs than Windows 95. Microsoft responded by promoting its own Doom port with a video of Bill Gates spliced into the game.',
  'Alexey Pajitnov wrote Tetris in 1984 at a Soviet computing center and earned nothing from it for years. The rights only reached him when The Tetris Company formed in 1996.',
  'In Pokemon Red and Blue, meeting the glitch Pokemon MissingNo multiplies the sixth item in your bag by 128. The bug survived into the 2016 3DS re-release, untouched.',
  'Chris Sawyer wrote about 99% of RollerCoaster Tycoon in x86 assembly language, by himself, and shipped it in 1999.',
  'EarthBound punished piracy in stages: bootleg copies threw far more enemies at you, then froze at the final battle and deleted every save file.',
  'The Atari landfill was real. Excavators in Alamogordo, New Mexico dug up cartridges on April 26, 2014, recovering about 1,300 of an estimated 728,000 buried in 1983.',
  'Howard Scott Warshaw built E.T. for the Atari 2600 in just over five weeks to make Christmas 1982. Roughly 3.5 million of the 4 million cartridges came back.',
  'The iPod was named by freelance copywriter Vinnie Chieco, who saw the white prototype and thought of "Open the pod bay doors, HAL" from 2001: A Space Odyssey.',
  'The original 2001 iPod hid a Breakout clone called Brick, reached by holding the center button on the About screen. Breakout was the arcade game Steve Wozniak designed in 1976.',
  'At Awesome Games Done Quick 2014, runners exploited an out-of-bounds function pointer in Super Mario World to run Pong and Snake inside the game, using nothing but controller inputs.',
  'In March 2016, SethBling performed arbitrary code execution on an unmodified SNES by hand, injecting Flappy Bird into Super Mario World in under an hour.',
  'The term "easter egg" comes from Atari\'s Adventure in 1980, where Warren Robinett hid a room reading "Created by Warren Robinett" because Atari refused to credit programmers.',
  "GoldenEye 007's multiplayer, the reason people remember it, was added about six months before release, largely by one programmer. The game sold over eight million copies.",
  'Shigeki Morimoto slipped Mew into Pokemon Red and Green just before launch, using space freed by stripping out debug code, after the team had been told to stop changing the game.',
  'The original Xbox ran a modified Windows 2000 kernel on a 733 MHz Pentium III, and was the first console with a hard drive built in. It held 8 GB.',
  'The PlayStation 2 played PS1 discs by using the original PlayStation processor as its I/O chip. It is still the best-selling console ever at about 160 million units.',
  'The iPhone was developed under the codename Project Purple starting in 2005 and launched June 29, 2007 at $499 for the 4 GB model.',
  'After the January 2007 iPhone reveal, Steve Jobs found his prototype screen scratched up by keys in his pocket. Apple got Corning to ship strengthened glass before the June launch, later branded Gorilla Glass.',
  'The Legend of Zelda in 1986 was the first console game that let you save your progress. Shigeru Miyamoto based its exploration on caves he found as a child near Sonobe, Japan.',
  'Donkey Kong existed in 1981 to salvage unsold Radar Scope arcade cabinets. Its hero was an unnamed carpenter called Jumpman, later renamed Mario.',
  'Nintendo was founded on September 23, 1889 to make hanafuda playing cards. Before video games it tried instant rice, love hotels, and a taxi company.',
  "The NES was deliberately shaped like a VCR so American retailers, burned by the 1983 crash, would stock it as electronics instead of a toy. The R.O.B. robot was part of the same disguise.",
  'At the Red Annihilation Quake tournament in May 1997, Dennis "Thresh" Fong won first prize: John Carmack\'s personal Ferrari 328.',
  'Windows Solitaire, bundled with Windows 3.0 in 1990, was written by an intern named Wes Cherry to teach people drag-and-drop. The card art was drawn by Susan Kare.',
  'Satoru Iwata, later Nintendo\'s CEO, wrote the graphics compression tools that let Pokemon Gold and Silver fit an entire second region onto the cartridge.',
  'Polish mathematician Marian Rejewski reconstructed the wiring of an Enigma machine he had never seen, in late 1932, using group theory. The British work at Bletchley started from his.',
  'Joan Clarke was the only woman to work as a Banburist at Bletchley Park, and her supervisor rated her among the best in the section.',
  'Clifford Cocks at GCHQ worked out the RSA algorithm in 1973, three years before Rivest, Shamir, and Adleman published it. It stayed classified until 1997.',
  'Malcolm Williamson at GCHQ discovered Diffie-Hellman key exchange in 1974, a year before the public version. He was not allowed to tell anyone for 23 years.',
  'Ron Rivest published MD5 as RFC 1321 in April 1992. By August 2004 researchers were generating collisions in about an hour on a cluster.',
  'On February 23, 2017, the SHAttered attack produced two different PDFs with the same SHA-1 hash, roughly 100,000 times faster than brute force. SHA-1 has been dying ever since.',
  'Kevin Mitnick broke into a Digital Equipment Corporation network at 16, in 1979. The FBI finally arrested him in Raleigh on February 15, 1995, and he served 46 months.',
  'John Draper found that the toy whistle in a box of Cap\'n Crunch produced a 2600 Hz tone, exactly the frequency the phone network used to signal a free line.',
  'In August 2001, Fluhrer, Mantin, and Shamir showed WEP keys could be recovered in about a minute. By 2005 the FBI was demonstrating the break in three minutes with public tools.',
  'Heartbleed was reported on April 1, 2014 by Neel Mehta of Google and patched six days later. It was a missing bounds check on a TLS keepalive message.',
  'Phil Zimmermann released PGP in 1991, then published the source code as a hardback book through MIT Press in 1995. Exporting software was a crime; exporting a book was speech.',
  'Al-Kindi described frequency analysis around 850 AD in Baghdad, the first known use of statistics to break a cipher. Every monoalphabetic cipher has been broken since.',
  'Friedrich Kasiski published the first general break of the Vigenere cipher in 1863. Evidence suggests Charles Babbage got there in 1854 and never bothered to publish.',
  "Rijndael, by Joan Daemen and Vincent Rijmen, won NIST's AES competition against 14 other designs after five years of public review. Choosing crypto in the open was the innovation.",
]

// One at random. The caller reads it once per mount, so the fact changes each
// time the pane opens rather than flickering on re-render.
export function randomFact(): string {
  return FACTS[Math.floor(Math.random() * FACTS.length)] ?? FACTS[0]!
}
